version: '3.1'

services:
  db:
    image: postgres
    container_name: sb_db
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: sea_battle
    ports: 
      - "5432:5432"
  server:
    build: .
    container_name: sb_server
    restart: always
    command: npm run dev
    volumes:
      - .:/serv
      - /usr/app/node_modules
    depends_on:
      - "db"
    ports:
      - "4000:4000"
